In [1]:
from pathlib import Path
import sys


project_root= Path.cwd().parent

if str(project_root) not in sys.path:
    sys.path.append(str(project_root))

from src.data.load_data import load_ai4i_dataset
from src.features.feature_engineering import (
    create_engineered_features
)
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df=load_ai4i_dataset()
df = create_engineered_features(df)

df.head()

,UDI,Product ID,Type,Air temperature [K],Process temperature [K],Rotational speed [rpm],Torque [Nm],Tool wear [min],Machine failure,TWF,HDF,PWF,OSF,RNF,Temperature Difference,Power Proxy,Mechanical Stress Index,Thermal Stress Index
0,1,M14860,M,298.1,308.6,1551,42.8,0,0,0,0,0,0,0,10.5,66382.8,0.027595,449.40
1,2,L47181,L,298.2,308.7,1408,46.3,3,0,0,0,0,0,0,10.5,65190.4,0.032884,486.15
2,3,L47182,L,298.1,308.5,1498,49.4,5,0,0,0,0,0,0,10.4,74001.2,0.032977,513.76
3,4,L47183,L,298.2,308.6,1433,39.5,7,0,0,0,0,0,0,10.4,56603.5,0.027565,410.80
4,5,L47184,L,298.2,308.7,1408,40.0,9,0,0,0,0,0,0,10.5,56320.0,0.028409,420.00

In [2]:
df.columns.tolist()

['UDI',
 'Product ID',
 'Type',
 'Air temperature [K]',
 'Process temperature [K]',
 'Rotational speed [rpm]',
 'Torque [Nm]',
 'Tool wear [min]',
 'Machine failure',
 'TWF',
 'HDF',
 'PWF',
 'OSF',
 'RNF',
 'Temperature Difference',
 'Power Proxy',
 'Mechanical Stress Index',
 'Thermal Stress Index']

In [3]:
engineered_features = [
    "Temperature Difference",
    "Power Proxy",
    "Mechanical Stress Index",
    "Thermal Stress Index",
    "Machine failure"
]

df[engineered_features].corr()["Machine failure"].sort_values(
    ascending=False
)

Machine failure            1.000000
Mechanical Stress Index    0.206493
Power Proxy                0.176039
Thermal Stress Index       0.123419
Temperature Difference    -0.111676
Name: Machine failure, dtype: float64

In [4]:
feature_columns = [
    "Type",
    "Air temperature [K]",
    "Process temperature [K]",
    "Rotational speed [rpm]",
    "Torque [Nm]",
    "Tool wear [min]",
    "Temperature Difference",
    "Power Proxy",
    "Mechanical Stress Index",
    "Thermal Stress Index"
]

df[feature_columns].head()

,Type,Air temperature [K],Process temperature [K],Rotational speed [rpm],Torque [Nm],Tool wear [min],Temperature Difference,Power Proxy,Mechanical Stress Index,Thermal Stress Index
0,M,298.1,308.6,1551,42.8,0,10.5,66382.8,0.027595,449.40
1,L,298.2,308.7,1408,46.3,3,10.5,65190.4,0.032884,486.15
2,L,298.1,308.5,1498,49.4,5,10.4,74001.2,0.032977,513.76
3,L,298.2,308.6,1433,39.5,7,10.4,56603.5,0.027565,410.80
4,L,298.2,308.7,1408,40.0,9,10.5,56320.0,0.028409,420.00

Feature Engineering Findings
1. Four engineered features were created.

2. Mechanical Stress Index exhibited the strongest correlation with machine failure.

3. Engineered features generally showed stronger predictive signal than several raw features.

4. Engineered features will be included in the modeling pipeline.